title: C# Advanced
description: This tutorial will cover advanced C# programming concepts 
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "Coding Skills.IO":
      - "https://rclapp.com"
footer_content: "Copyright &copy; 2020 Ray Consulting Limited - Coding Skills.IO."
plugins:
  - jekyll-seo-tag